#Concierge & Customer application
ENVIRONMENT_CONCIERGE_RESOURCEPOINT="/concierge/"
ENVIRONMENT_CONCIERGE_USER="user"
ENVIRONMENT_CONCIERGE_PASSWORD="bm90IGEgcmVhbCByZXBv"
ENVIRONMENT_ADVICE_HOSTURL="https://robot.charter.com.au"
ENVIRONMENT_CUSTOMER_RESOURCEPOINT="/customer/"
ENVIRONMENT_CONCIERGE_USER_ADMIN = "admin"
ENVIRONMENT_CONCIERGE_PASSWORD_ADMIN = "admin"
ENVIRONMENT_CUSTOMERREGISTRATION="/customer/registernew?source=e1337"
